package certificate;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.swing.JOptionPane;

public class BookingForm extends javax.swing.JFrame {

    String selectedGender = null;
    int comboBox =0;
   Connection con =null;
    PreparedStatement pst =null;
    public BookingForm() {
        initComponents();
         province.addItem("Gauteng");
        province.addItem("KwaZulu Natal");
        province.addItem("Free State");
        province.addItem("Western Cape");
        province.addItem("Eastern Cape");
        province.addItem("Northern Cape");
        province.addItem("Mpumalanga");
        province.addItem("Limpopo");
        province.addItem("North West");
        
        IDtype.addItem("RSA ID DOCUMENT");
        IDtype.addItem("FOREIGN ID DOCUMENT");
        
        language.addItem("ENGLISH");
        language.addItem("AFRIKAANS");
        language.addItem("ZULU");
        language.addItem("XHOSA");
        language.addItem("SOTHO");
        language.addItem("PEDI");
        language.addItem("SWATI");
        language.addItem("NDEBELE");
        language.addItem("TSWANA");
        language.addItem("VENDA");
        language.addItem("TSONGA");
    
       
    }

    public void buttonGroup(){
        buttonGroup1.add(radioMale);
        buttonGroup1.add(radioFemale);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Booking = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        province = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        IDtype = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtnames = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtsurname = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        language = new javax.swing.JComboBox<>();
        nBookingF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPost = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        txtCellNo2 = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        txtCellNo = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        radioFemale = new javax.swing.JRadioButton();
        radioMale = new javax.swing.JRadioButton();
        lblNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblConfirmNo = new javax.swing.JLabel();
        lblAdd1 = new javax.swing.JLabel();
        lblAdd2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Booking.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel97.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("BOOKING FORM");
        jPanel1.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 19, -1, -1));

        province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT PROVINCE" }));
        province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceActionPerformed(evt);
            }
        });

        jLabel37.setText("IDENTIFICATION TYPE:");

        jLabel38.setText("IDENTIFICATION NUMBER:");

        jLabel39.setText("SURNAME:");

        jLabel40.setText("NAMES:");

        IDtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT IDENTIFICATION TYPE" }));
        IDtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtypeActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 153, 255));
        jLabel41.setText("IDENTIFY APPLICANT");

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 153, 255));
        jLabel42.setText("PERSON DETAILS");

        txtnames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnamesKeyReleased(evt);
            }
        });

        jLabel46.setText("PREFERRED LANGUAGE:");

        jLabel47.setText("GENDER:");

        txtsurname.setPreferredSize(new java.awt.Dimension(64, 20));
        txtsurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsurnameKeyReleased(evt);
            }
        });

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT LANGUAGE" }));
        language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageActionPerformed(evt);
            }
        });

        nBookingF.setBackground(new java.awt.Color(51, 153, 255));
        nBookingF.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        nBookingF.setForeground(new java.awt.Color(255, 255, 255));
        nBookingF.setText("Next");
        nBookingF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nBookingFMouseClicked(evt);
            }
        });
        nBookingF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBookingFActionPerformed(evt);
            }
        });

        jLabel2.setText("PROVINCES:");

        txtPost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPostKeyReleased(evt);
            }
        });

        jLabel100.setText("POSTAL CODE:");

        txtAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress2ActionPerformed(evt);
            }
        });

        jLabel101.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(51, 153, 255));
        jLabel101.setText("RESIDENTIAL ADDRESS");

        jLabel102.setText("STREET ADDRESS LINE 2");

        jLabel103.setText("CITY:");

        jLabel104.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(51, 153, 255));
        jLabel104.setText("CONTACT DETAILS");

        jLabel105.setText("CELLPHONE NUMBER:");

        jLabel106.setText("EMAIL ADDRESS:");

        txtCellNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellNoActionPerformed(evt);
            }
        });
        txtCellNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCellNoKeyReleased(evt);
            }
        });

        jLabel107.setText("CONFIRM CELLPHONE NUMBER:");

        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });

        jLabel108.setText("STREET ADDRESS:");

        buttonGroup1.add(radioFemale);
        radioFemale.setText("FEMALE");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMale);
        radioMale.setText("MALE");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });

        lblNo.setForeground(new java.awt.Color(255, 0, 0));

        lblEmail.setForeground(new java.awt.Color(255, 0, 0));

        lblName.setForeground(new java.awt.Color(255, 0, 0));

        lblSurname.setForeground(new java.awt.Color(255, 0, 0));

        lblCode.setForeground(new java.awt.Color(255, 0, 0));

        lblConfirmNo.setForeground(new java.awt.Color(255, 51, 51));

        lblAdd1.setForeground(new java.awt.Color(255, 0, 0));

        lblAdd2.setForeground(new java.awt.Color(255, 0, 0));

        lblCity.setForeground(new java.awt.Color(255, 0, 0));

        lblID.setForeground(new java.awt.Color(255, 0, 0));

        lblGender.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout BookingLayout = new javax.swing.GroupLayout(Booking);
        Booking.setLayout(BookingLayout);
        BookingLayout.setHorizontalGroup(
            BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BookingLayout.createSequentialGroup()
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel37)
                        .addGap(231, 231, 231)
                        .addComponent(jLabel38))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel40)
                        .addGap(307, 307, 307)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel47))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel46))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel104))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel105)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel107))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCellNo2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(lblConfirmNo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel106))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel101))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel108)
                        .addGap(262, 262, 262)
                        .addComponent(jLabel102))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txtnames, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                        .addGap(90, 90, 90)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsurname, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(lblSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IDtype, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookingLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookingLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel100)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookingLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(nBookingF, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(radioFemale))
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioMale)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        BookingLayout.setVerticalGroup(
            BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(12, 12, 12)
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDtype, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel40))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)))
                .addGap(3, 3, 3)
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addComponent(txtnames, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioFemale)
                            .addComponent(radioMale)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel46)
                        .addGap(7, 7, 7)
                        .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel104)
                        .addGap(18, 18, 18)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel105)
                            .addComponent(jLabel107)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addComponent(txtsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addComponent(txtCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel106)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addComponent(txtCellNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConfirmNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel101)
                .addGap(18, 18, 18)
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel108)
                            .addComponent(jLabel102))
                        .addGap(18, 18, 18)
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel103)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(nBookingF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(Booking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceActionPerformed

    }//GEN-LAST:event_provinceActionPerformed

    private void languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageActionPerformed

    private void nBookingFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nBookingFMouseClicked

    }//GEN-LAST:event_nBookingFMouseClicked

    private void nBookingFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBookingFActionPerformed

//        java.util.Date selectedDate = date.getDate();
//        Calendar dobCalendar = new GregorianCalendar();
//        dobCalendar.setTime(selectedDate);
//
//        Calendar today = Calendar.getInstance();
//        today.add(Calendar.YEAR, -16);

       String name = txtnames.getText();
       String surname = txtsurname.getText();
       String IDno = txtID.getText();
       String cellNo = txtCellNo.getText();
       String confirmNo = txtCellNo2.getText();
       String emailAddress = txtEmailAddress.getText();
       String Address1 = txtAddress1.getText();
       String Address2 = txtAddress2.getText();
       String City = txtCity.getText();
       String postalCode = txtPost.getText();
       String IDnoType = (String) IDtype.getSelectedItem();
       
       
       
       boolean hasError = false;
       
       if (name.isEmpty()) {
           lblName.setText("Full Name is required");
           hasError = true;
           } else if (!name.matches("^[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)?$")) {
               lblName.setText("Full Name should only contain letters");
               hasError = true;
               }  
           else {
               lblName.setText(null);
               }
       if (surname.isEmpty()) {
           lblSurname.setText("Surname is required");
           hasError = true;
           } else if (!surname.matches("^[a-zA-Z]*$")) {
               lblSurname.setText("Full Name should only contain letters");
               hasError = true;
               }  
           else {
               lblSurname.setText(null);
               }
        if (emailAddress.isEmpty()) {
            lblEmail.setText("Email is required");
            hasError = true;
            } 
        else if (!emailAddress.contains("@") || !emailAddress.contains(".")) {
            lblEmail.setText("The email is invalid");
            hasError = true;
            } 
        else {
            lblEmail.setText(null);
            }

       if (IDno.isEmpty()) {
    lblID.setText("The ID number is required");
    hasError = true;
       } 
       
       else if (!IDno.matches("^[0-9]{13}$")) {
           lblID.setText("ID Number should be 13 digits");
           hasError = true;
           } 
       else {
           lblID.setText(null); // Clear the error message when there's no error
}
       if (cellNo.isEmpty()) {
           lblNo.setText("The cellphone number is required");
           hasError = true;
           } 
       else if (!cellNo.matches("^0[0-9]{9}$")) {
           lblNo.setText("Number should start with '0' and be 10 digits in total");
           hasError = true;
           } 
       else {
           lblNo.setText(null); // Clear the error message when there's no error
           }
       
       if (confirmNo.isEmpty()) {
           lblConfirmNo.setText("The confirmation number is required");
           hasError = true;
           } 
       else if (!confirmNo.equals(cellNo)) {
           lblConfirmNo.setText("Confirmation number does not match the cellphone number");
           hasError = true;
           } 
       else {
           lblConfirmNo.setText(null); // Clear the error message when there's no error
           }
   
      if(postalCode.isEmpty()){
           lblCode.setText("The zip code is required");
           hasError = true;
       }
       else if (!postalCode.matches("^[0-9]{4}$")) {
    lblCode.setText("Zip Code should be 4 digits");
    hasError = true;
       }
       else{
           lblCode.setText(null);
       } 
       
    if (Address1.isEmpty()) {
    lblAdd1.setText("Address is required");
    hasError = true;
} else {
    lblAdd1.setText(null);
}
    if (Address2.isEmpty()) {
    lblAdd2.setText("Address is required");
    hasError = true;
} else {
    lblAdd2.setText(null);
}
    if (City.isEmpty()) {
    lblCity.setText("City is required");
    hasError = true;
} else {
    lblCity.setText(null);
}
  if (IDnoType == null || IDnoType.isEmpty()) {
    lblGender.setText("ID Type is required"); // Display an error message if no type is selected
    hasError = true;
} else {
    lblGender.setText(null); // Clear the error message if a type is selected
}  
    
    final String[] radioButtonSelection = {null}; // Initialize the variable

//    radioFemale.addActionListener(new ActionListener() {
//    public void actionPerformed(ActionEvent e) {
//        if (radioFemale.isSelected()) {
//            radioButtonSelection[0] = "FEMALE";
//        }
//    }
//});
//
//    radioMale.addActionListener(new ActionListener() {
//    public void actionPerformed(ActionEvent e) {
//        if (radioMale.isSelected()) {
//            radioButtonSelection[0] = "MALE";
//        }
//    }
//});
//        
//  if (dobCalendar.after(today)) {
//    JOptionPane.showMessageDialog(rootPane, "You must be at least 16 years old to proceed");
//    hasError = true;
//}  
    if (!hasError){
        try{
          String query = "INSERT INTO `booking`(`name`, `surname`,`IdType`, `IDNo`, `phoneNo`, `confirmNo`, `emailAddress`, `address1`, `address2`, `city`, `postCode`, `gender`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/driving_school", "root","");
          pst=con.prepareStatement(query);
          pst.setString(1, txtnames.getText());
          pst.setString(2, txtsurname.getText());
          pst.setString(3, IDnoType);
          pst.setString(4, txtID.getText());
          pst.setString(5, txtCellNo.getText());
          pst.setString(6, txtCellNo2.getText());
          pst.setString(7, txtEmailAddress.getText());
          pst.setString(8, txtAddress1.getText());
          pst.setString(9, txtAddress2.getText());
          pst.setString(10, txtCity.getText());
          pst.setString(11, txtPost.getText());
          pst.setString(12, selectedGender);
          
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "SUCCESSFULLY BOOKED FOR TEST APPOINTMENT");
         
          
          Payment1 billingForm = new Payment1();
            billingForm.setVisible(true);
            dispose();
          dispose();
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }
         
        
    
       }
    
    }//GEN-LAST:event_nBookingFActionPerformed

    private void txtAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress2ActionPerformed

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
         if (radioMale.isSelected()) {
            selectedGender = "MALE";
        }
    }//GEN-LAST:event_radioMaleActionPerformed

    private void txtCellNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellNoKeyReleased

    }//GEN-LAST:event_txtCellNoKeyReleased

    private void txtPostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostKeyReleased
 
    }//GEN-LAST:event_txtPostKeyReleased

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased

    }//GEN-LAST:event_txtIDKeyReleased

    private void txtnamesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamesKeyReleased

    }//GEN-LAST:event_txtnamesKeyReleased

    private void txtsurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsurnameKeyReleased
   
    }//GEN-LAST:event_txtsurnameKeyReleased

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased

    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtCellNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellNoActionPerformed

    private void IDtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtypeActionPerformed

         if(province.getSelectedItem().equals("RSA ID DOCUMENT")) {
           txtID.setText("ID Number should be 13 digits");
       }
         else if(province.getSelectedItem().equals("FOREIGN ID DOCUMENT")) {
           txtID.setText("ID Number should be between 2 to 13 digits");
       }
    }//GEN-LAST:event_IDtypeActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        
        if (radioFemale.isSelected()) {
            selectedGender = "FEMALE";
        }
    }//GEN-LAST:event_radioFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Booking;
    private javax.swing.JComboBox<String> IDtype;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> language;
    private javax.swing.JLabel lblAdd1;
    private javax.swing.JLabel lblAdd2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblConfirmNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JButton nBookingF;
    private javax.swing.JComboBox<String> province;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCellNo;
    private javax.swing.JTextField txtCellNo2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPost;
    private javax.swing.JTextField txtnames;
    private javax.swing.JTextField txtsurname;
    // End of variables declaration//GEN-END:variables
}
