/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certificate;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class Payment1 extends javax.swing.JFrame {

    Connection con =null;
    PreparedStatement pst =null;
    public Payment1() {
        initComponents();
        
        
        //this.jComboProv.addItem("Select");
        this.jComboProv.addItem("Gauteng");
        jComboProv.addItem("KwaZulu Natal");
        jComboProv.addItem("Free State");
        jComboProv.addItem("Western Cape");
        jComboProv.addItem("Eastern Cape");
        jComboProv.addItem("Northern Cape");
        jComboProv.addItem("Mpumalanga");
        jComboProv.addItem("Limpopo");
        jComboProv.addItem("North West");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCard = new javax.swing.JTextField();
        txtValid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboProv = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAdd = new javax.swing.JTextField();
        txtCardNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPostal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCardName = new javax.swing.JLabel();
        lblCardNo = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblValidTime = new javax.swing.JLabel();
        lblPro = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblCVV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 300, 31));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BILLING ADDRESS ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 31));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Certificate\\src\\images\\payment-methods.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 350, 50));
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 330, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Full Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, 100, 20));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 330, 30));
        jPanel1.add(txtCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 350, 30));
        jPanel1.add(txtValid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 210, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("City :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 100, 20));

        jComboProv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel1.add(jComboProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 140, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Province :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("CVV :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 100, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Accepted Cards :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 100, 20));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 330, 30));
        jPanel1.add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 30));
        jPanel1.add(txtCardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 340, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Name On Card :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 100, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Card Number :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 100, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Valid Thru :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 100, 20));
        jPanel1.add(txtCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 150, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Postal Code :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, 20));
        jPanel1.add(txtPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 150, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Proceed To CheckOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 290, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 330, -1));

        lblCardName.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblCardName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblCardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 350, -1));

        lblCardNo.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblCardNo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblCardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 340, -1));

        lblAddress.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 330, -1));

        lblCity.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 330, -1));

        lblValidTime.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblValidTime.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 210, -1));

        lblPro.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblPro.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, -1));

        lblZipCode.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblZipCode.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 150, -1));

        lblCVV.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblCVV.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      String fullname = txtName.getText();
      String email = txtEmail.getText();
      String cardname = txtCard.getText();
      String cardnumber = txtCardNo.getText();
      String address = txtAdd.getText();
      String city = txtCity.getText();
      String expdate = txtValid.getText();
      String province = (String)jComboProv.getSelectedItem();
      String postcode = txtPostal.getText();
      String cvv = txtCVV.getText();
        
     boolean hasError = false;
     
     if (fullname.isEmpty()) {
         
        lblName.setText("Full Name is required");
        hasError = true;
        } 
     else if (!fullname.matches("^[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)?$")) {
    lblName.setText("Full Name should only contain letters");
    hasError = true;
    } 
     else {
    lblName.setText(null);
     }

     if (email.isEmpty()) {
    lblEmail.setText("Email is required");
    hasError = true;
    }
     else if (!email.contains("@") || !email.contains(".")) {
    lblEmail.setText("The email is invalid");
    hasError = true;

     } else {
    lblEmail.setText(null);

     }

     if (cardname.isEmpty()) {
    lblCardName.setText("Card Name is required");
    hasError = true;

     } 
     else if (!cardname.matches("^[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)?$")) {
    lblCardName.setText("Card Name should only contain letters");
    hasError = true;
     } else {
         lblCardName.setText(null);
         }
     if (cardnumber.isEmpty()) {
    lblCardNo.setText("Card Number is required");
    hasError = true;
} else if (!cardnumber.matches("^[0-9]{16}$")) {
    lblCardNo.setText("Card Number should be 16 digits");
    hasError = true;
} else {
    lblCardNo.setText(null);
}

if (address.isEmpty()) {
    lblAddress.setText("Address is required");
    hasError = true;
} else {
    lblAddress.setText(null);
}

if (city.isEmpty()) {
    lblCity.setText("City is required");
    hasError = true;
} else {
    lblCity.setText(null);
}

if (expdate.isEmpty()) {
    lblValidTime.setText("Expiry Date is required");
    hasError = true;
} else if (!expdate.matches("^(0[1-9]|1[0-2])/(\\d{4})$")) {
    lblValidTime.setText("Expiry Date should be in the format MM/YYYY");
    hasError = true;
} else {
    lblValidTime.setText(null);
}

if (postcode.isEmpty()) {
    lblZipCode.setText("Zip Code is required");
    hasError = true;
} else if (!postcode.matches("^[0-9]{4}$")) {
    lblZipCode.setText("Zip Code should be 4 digits");
    hasError = true;
} else {
    lblZipCode.setText(null);
}

if (cvv.isEmpty()) {
    lblCVV.setText("CVV is required");
    hasError = true;
} else if (!cvv.matches("^[0-9]{3}$")) {
    lblCVV.setText("CVV should be 3 digits");
    hasError = true;
} else {
    lblCVV.setText(null);
}

if (province == null || province.isEmpty()) {
    lblPro.setText("Province is required"); // Display an error message if no type is selected
    hasError = true;
} else {
    lblPro.setText(null); // Clear the error message if a type is selected
}  

if (!hasError){
        try{
            String query = "INSERT INTO `payment` (`fullname`, `email`, `cardname`, `cardnumber`, `address`, `city`, `expdate`, `province`, `postcode`, `cvv`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
          
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/driving_school", "root","");
          pst=con.prepareStatement(query);
          pst.setString(1, txtName.getText());
          pst.setString(2, txtEmail.getText());
          pst.setString(3, txtCard.getText());
          pst.setString(4, txtCardNo.getText());
          pst.setString(5, txtAdd.getText());
          pst.setString(6, txtCity.getText());
          pst.setString(7, txtValid.getText());
          province = jComboProv.getSelectedItem().toString();
          pst.setString(8, province);
          
          pst.setString(9, txtPostal.getText());
          pst.setString(10, txtCVV.getText());
          
                    
          
           int dialog = JOptionPane.YES_NO_OPTION;
           int result = JOptionPane.showConfirmDialog(null,"Proceed Payment?","Exit", dialog);
           
           dispose();

        ProofOfPayment pay = new ProofOfPayment();
        pay.setTitle("Dashboard");
        pay.setLocationRelativeTo(null);
        pay.setVisible(true);
        pay.print.setText(pay.print.getText()+ " " + txtName.getText()+ "\n\n");
         pay.print.setText(pay.print.getText()+ " " + txtEmail.getText()+"\n\n");
         pay.print.setText(pay.print.getText()+ " " + txtAdd.getText()+ "\n\n");
         pay.print.setText(pay.print.getText()+ " " + txtCity.getText() + "\n\n");
         pay.print.setText(pay.print.getText()+ " " + txtPostal.getText()+ "\n\n");
         pay.print.setText(pay.print.getText() + " " + jComboProv.getSelectedItem() + "\n\n");

         
           
          int k = pst.executeUpdate();
           
        
        

//          if(k == 1){
//               //JOptionPane.showMessageDialog(null, "PROCEED PAYMENT ?", "YES",dialog);
//               txtName.setText("");
//           txtEmail.setText("");
//           jComboProv.setSelectedItem("");
//          txtCVV.setText("");
//        txtCard.setText("");
//          txtCardNo.setText("");
//         txtAdd.setText("");
//          txtValid.setText("");
//          txtPostal.setText("");
//          txtCity.setText("");
//          ProofOfPayment slip = new ProofOfPayment();
//              slip.show();
//              dispose();
              
//          }
//          else{
//              JOptionPane.showMessageDialog(null, "We couldn't process your payment please try again");
//          }
//          
//          
//              ProofOfPayment slip = new ProofOfPayment();
//              slip.setAlwaysOnTop(true);
          
          
         
          
         // StuBooking billingForm = new StuBooking();
          //  billingForm.setVisible(true);
          //  dispose();
          //dispose();
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }
         
        
    
        







    }                                        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblCardName;
    private javax.swing.JLabel lblCardNo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblValidTime;
    private javax.swing.JLabel lblZipCode;
    public javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCard;
    private javax.swing.JTextField txtCardNo;
    public javax.swing.JTextField txtCity;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPostal;
    private javax.swing.JTextField txtValid;
    // End of variables declaration//GEN-END:variables
}
