/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certificate;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class ProofOfPayment extends javax.swing.JFrame {

    /**
     * Creates new form ProofOfPayment
     */
    public ProofOfPayment() {
        initComponents();
        type.addItem("Driver's Lisense");
        type.addItem("Learner's Lisense");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblActivity = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        print = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("What are you booking for?");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, 220, 30));

        type.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeItemStateChanged(evt);
            }
        });
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 310, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amount Due :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 20));
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Cancel Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setText("Continue Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));
        jPanel2.add(lblActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 20));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 54, 400, 350));

        print.setColumns(20);
        print.setRows(5);
        jScrollPane1.setViewportView(print);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 340, 390));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("PROCEED TO PAY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 270, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeItemStateChanged
        // TODO add your handling code here:
        if (type.getSelectedItem().equals("Driver's Lisense")){
            amount.setText("2000");
        }else if (type.getSelectedItem().equals("Learner's Lisense")){
            amount.setText("1500");
        }
    }//GEN-LAST:event_typeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String activity = (String) type.getSelectedItem();
        String payment = amount.getText();
        
        boolean hasError = false;
        
        if (activity == null || activity.isEmpty()) {
    lblActivity.setText("Activity is required"); // Display an error message if no type is selected
    hasError = true;
} else {
    lblActivity.setText(null); // Clear the error message if a type is selected
} 
        
        if (!hasError){
        try{
            String query = "INSERT INTO `payment_proof` (`activity`, `payment`) VALUES ( ?, ?) ";
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/driving_school", "root","");
            PreparedStatement pst = con.prepareStatement(query);
          activity = type.getSelectedItem().toString();
          pst.setString(1, activity);
          pst.setString(2, amount.getText());
          
          int dialog = JOptionPane.YES_NO_OPTION;
           int result = JOptionPane.showConfirmDialog(null,"Proceed Payment?","Payment", dialog);
           print.setText(print.getText() + " " + type.getSelectedItem() + "\n\n");
           print.setText(print.getText()+ " " + amount.getText()+ "\n\n");
           Date obj=new Date();
         String date =obj.toString();
         print.setText(print.getText()+ " " + date);
          int p = pst.executeUpdate();
          
          if(p == 1){
               amount.setText("");
               type.setSelectedItem("");
          }else{
              JOptionPane.showMessageDialog(null, "Your Payment was Unsuccessful");
          }
        }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"Do you really want to Cancel","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

                    
          PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Print Data");

    job.setPrintable(new Printable() {
        @Override
        public int print(Graphics g, PageFormat pf, int pageNum) throws PrinterException {
            pf.setOrientation(PageFormat.LANDSCAPE);

            if (pageNum > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            Graphics2D graphics2D = (Graphics2D) g;
            double scaleFactor = 0.55;

            // Calculate the dimensions of the panel after scaling
            double panelWidth = jPanel1.getWidth() * scaleFactor;
            double panelHeight = jPanel1.getHeight() * scaleFactor;

            // Calculate the position to center the content vertically
            double x = (pf.getImageableWidth() - panelWidth) / 2.0;
            double y = (pf.getImageableHeight() - panelHeight) / 2.0;

            // Adjust the translation to center the content both horizontally and vertically
            graphics2D.translate(pf.getImageableX() + x, pf.getImageableY() + y);
            graphics2D.scale(scaleFactor, scaleFactor);

            print.print(graphics2D);

            return Printable.PAGE_EXISTS;
        }
    });

    boolean ok = job.printDialog();

    if (ok) {
        try {
            job.print();
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }
//        Payment1 pay = new Payment1();
//        pay.setTitle("Dashboard");
//        pay.setLocationRelativeTo(null);
//        pay.setVisible(true);
        
//        print.setText(print.getText()+ " " + pay.txtName.getText()+ "\n\n");
//        print.setText(print.getText()+ " " + pay.txtEmail.getText()+"\n\n");
//        print.setText(print.getText()+ " " + pay.txtAdd.getText()+ "\n\n");
//        print.setText(print.getText()+ " " + pay.txtCity.getText() + "\n\n");
//        print.setText(print.getText()+ " " + pay.txtPostal.getText()+ "\n\n");
//         Date obj=new Date();
//         String date =obj.toString();
//        print.setText(print.getText()+ " " + date);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProofOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProofOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProofOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProofOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProofOfPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActivity;
    public javax.swing.JTextArea print;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
